# Generated by Django 4.2.5 on 2023-09-28 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Имя продукта')),
                ('allergy', models.BooleanField(default=True, verbose_name='Аллергия')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='FridgeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(verbose_name='Количество')),
                ('measure', models.IntegerField(verbose_name='Количество')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fridge_products', to='dbcore.product')),
            ],
            options={
                'verbose_name': 'Продукт в холодильнике',
                'verbose_name_plural': 'Продукты в холодильнике',
            },
        ),
    ]
