# Generated by Django 4.2.5 on 2023-09-29 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure', models.CharField(max_length=255, verbose_name='Мера')),
            ],
            options={
                'verbose_name': 'Мера',
                'verbose_name_plural': 'Меры',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Имя продукта')),
                ('allergy', models.BooleanField(default=False, verbose_name='Аллергия')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.CreateModel(
            name='RecipeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(verbose_name='Количество')),
                ('measure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_products', to='dbcore.measure')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_products', to='dbcore.product', verbose_name='Продукт')),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_products', to='dbcore.recipe', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'Продукт для рецепта',
                'verbose_name_plural': 'Продукты для рецептов',
            },
        ),
        migrations.CreateModel(
            name='FridgeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(verbose_name='Количество')),
                ('measure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fridge_products', to='dbcore.measure')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fridge_products', to='dbcore.product')),
            ],
            options={
                'verbose_name': 'Продукт в холодильнике',
                'verbose_name_plural': 'Продукты в холодильнике',
            },
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('recipe', models.ManyToManyField(related_name='calendars', to='dbcore.recipe')),
            ],
            options={
                'verbose_name': 'Календарь',
                'verbose_name_plural': 'Календарь',
            },
        ),
        migrations.CreateModel(
            name='AllergyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allergy_products', to='dbcore.product')),
            ],
            options={
                'verbose_name': 'Аллергия на продукт',
                'verbose_name_plural': 'Аллергии на продукты',
            },
        ),
    ]
