# Generated by Django 4.2.5 on 2023-09-29 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbcore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='recipe',
        ),
        migrations.AddField(
            model_name='calendar',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='dbcore.recipe'),
            preserve_default=False,
        ),
    ]
