# Generated by Django 4.2.5 on 2023-09-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbcore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='allergy',
            field=models.BooleanField(default=False, verbose_name='Аллергия'),
        ),
    ]
