# Generated by Django 4.2.5 on 2023-09-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbcore', '0002_alter_product_allergy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridgeproduct',
            name='measure',
            field=models.CharField(max_length=255, verbose_name='Мера'),
        ),
    ]
