# Generated by Django 4.2.5 on 2023-09-28 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbcore', '0004_mesure_alter_fridgeproduct_measure'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mesure',
            new_name='Measure',
        ),
    ]
