# Generated by Django 4.2.5 on 2023-09-28 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbcore', '0005_rename_mesure_measure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Имя продукта')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.AlterModelOptions(
            name='measure',
            options={'verbose_name': 'Мера', 'verbose_name_plural': 'Меры'},
        ),
        migrations.CreateModel(
            name='RecipeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(verbose_name='Количество')),
                ('measure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_products', to='dbcore.measure')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_products', to='dbcore.product', verbose_name='Продукт')),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_products', to='dbcore.recipe', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'Продукт для рецепта',
                'verbose_name_plural': 'Продукты для рецептов',
            },
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('recipe', models.ManyToManyField(to='dbcore.recipe')),
            ],
        ),
    ]
