# Generated by Django 4.2.5 on 2023-09-28 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbcore', '0006_recipe_alter_measure_options_recipeproduct_calendar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendar',
            options={'verbose_name': 'Календарь', 'verbose_name_plural': 'Календарь'},
        ),
        migrations.CreateModel(
            name='AllergyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allergy_products', to='dbcore.product')),
            ],
            options={
                'verbose_name': 'Аллергия на продукт',
                'verbose_name_plural': 'Аллергии на продукты',
            },
        ),
    ]
